#!/usr/bin/env python3
"""
x-analyst - Main Entry Point
Generated by masumi init

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""
import os
import sys
from dotenv import load_dotenv
from agent import process_job

# Load environment variables from .env file
load_dotenv()

# Check for standalone mode
STANDALONE = "--standalone" in sys.argv

# Define input schema
# Masumi expects {"input_data": [...]} format for MIP-003 compliance
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "analysis_type",
            "type": "option",
            "name": "Analysis Type",
            "data": {
                "description": "Type of analysis to perform",
                "values": ["sentiment", "summary", "stats", "keywords", "recommendations", "general"],
                "default": "general"
            },
            "validations": [
                {"validation": "required", "value": "true"}
            ]
        },
        {
            "id": "text",
            "type": "text",
            "name": "Text Input",
            "data": {
                "description": "Text to analyze (required for sentiment, summary, stats, keywords, general)",
                "placeholder": "Enter text to analyze (minimum 10 characters, maximum 100,000 characters)"
            },
            "validations": [
                {"validation": "min", "value": "10"},
                {"validation": "max", "value": "100000"}
            ]
        },
        {
            "id": "user_history",
            "type": "text",
            "name": "User Engagement History",
            "data": {
                "description": "Required for recommendations: JSON array of user's past engagements",
                "placeholder": '[{"post_id": "post1", "action": "like", "timestamp": 1734567890}]'
            },
            "validations": []
        },
        {
            "id": "candidates",
            "type": "text",
            "name": "Candidate Posts",
            "data": {
                "description": "Required for recommendations: JSON array of posts to rank",
                "placeholder": '[{"post_id": "cand1", "text": "Breaking news about AI", "author_id": "user123", "media_type": "text"}]'
            },
            "validations": []
        },
        {
            "id": "max_keywords",
            "type": "number",
            "name": "Maximum Keywords",
            "data": {
                "description": "Maximum number of keywords to extract (1-100, default: 10)"
            },
            "validations": [
                {"validation": "min", "value": "1"},
                {"validation": "max", "value": "100"},
                {"validation": "format", "value": "integer"}
            ]
        },
        {
            "id": "summary_sentences",
            "type": "number",
            "name": "Summary Sentences",
            "data": {
                "description": "Number of sentences in summary (1-20, default: 3)"
            },
            "validations": [
                {"validation": "min", "value": "1"},
                {"validation": "max", "value": "20"},
                {"validation": "format", "value": "integer"}
            ]
        },
        {
            "id": "top_k",
            "type": "number",
            "name": "Top K Recommendations",
            "data": {
                "description": "Number of top recommendations to return (1-100, default: 10)"
            },
            "validations": [
                {"validation": "min", "value": "1"},
                {"validation": "max", "value": "100"},
                {"validation": "format", "value": "integer"}
            ]
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    if STANDALONE:
        # Standalone mode - for testing without blockchain
        import asyncio
        import json

        async def test_standalone():
            print("\n=== X-Analyst Standalone Mode ===")
            print("Enter job input (JSON format):")
            print('Example: {"text": "This is amazing!", "analysis_type": "sentiment"}')

            try:
                input_str = input("\nInput: ")
                input_data = json.loads(input_str)

                print("\nProcessing...")
                result = await process_job("standalone-test-id", input_data)

                print("\n=== Result ===")
                print(json.dumps(result, indent=2))
            except json.JSONDecodeError as e:
                print(f"Invalid JSON: {e}")
            except Exception as e:
                print(f"Error: {e}")

        asyncio.run(test_standalone())
    else:
        # API mode - use MasumiAgentServer directly
        import uvicorn
        from masumi import MasumiAgentServer

        # Create server (reads config from environment variables)
        server = MasumiAgentServer(
            start_job_handler=process_job,
            input_schema_handler=INPUT_SCHEMA
        )

        # Get FastAPI app
        app = server.app

        # Run server
        host = os.getenv("HOST", "0.0.0.0")
        port = int(os.getenv("PORT", 8080))

        print(f"Starting X-Analyst on {host}:{port}")
        uvicorn.run(app, host=host, port=port)
